### ISSUE TITLE
Zenny

### ISSUE THREAD

**Issue by Kadaz** [ivanlamega/dragon-ball-online-tw-server#18]
Zenny goes to 0 after relogin or after starting the server.

**Comment by Kadaz** [comment]
I change the valie from the database but it didnt fix this bug. I also notice that the bank doesnt load correctly and i remember that zenny updated together with the bank in akcore server. Maybe we have to do something similar in this sourse. Why the table name is zenny and not money here?

**Comment by ThatOneDBOGuy** [comment]
It's because we have to load the zenny from the database. I will work on that later today

**Comment by Kadaz** [comment]
xm ok. The same goes with exp. It only remember how match exp we have when we level up. Now i am reading the quickslot because it doent remember action skills like attack, pick up ect. I`ll try some triks i have in my mind.

**Comment by ivanlamega** [comment]
It's easy, just save the zenny and the exp in the database in LogoutPlayer
https://github.com/ivanlamega/dragon-ball-online-tw-server/blob/4a42be52103d9397763ad925b953d190a42c51b9/GameServer/Source/CPP/Game/World/WorldSession.cpp

I would do it, but I can't prove it right now, I could modify it but not try it.

**Comment by Kadaz** [comment]
Intresting. Maybe we can do it for bank too. At least for the zenny.

**Comment by Kadaz** [comment]
Database doent update the zenny or exp so even if we save in logout it will return 0.

**Comment by Kadaz** [comment]
I think...

**Comment by ivanlamega** [comment]
Try it now, the game should save the player's zenny.
