### ISSUE TITLE
Boost files right locacion

### ISSUE THREAD

**Issue by Kaible84** [ivanlamega/dragon-ball-online-tw-server#2]
Hello. I unzip the boost folder inside the dragonball online tw server master but it gives me errors about boost files when i try to compile in x64 mode. Shall i put the boost folder someware else? I use ultimate 2015 vb.

**Comment by ThatOneDBOGuy** [comment]
For this source, you do not need the boost files like with AKCore! The package folder from the mega link in the readme.md is the only file you need to compile this source.

**Comment by Kaible84** [comment]
Tnx for the replay. The package folder i mean. Shall i put it directly to the dragonball online tw server master or to a spesific file inside the project?

**Comment by ivanlamega** [comment]
In the main folder

**Comment by Kaible84** [comment]
alright. tnx a lot.
