### ISSUE TITLE
Compiling errors in vb 2015 (eUnzipper unavailale)

### ISSUE THREAD

**Issue by Kadaz** [ivanlamega/dragon-ball-online-tw-server#3]
dragon-ball-online-tw-server-master\Tools\eUnzipper\eUnzipper.vcxproj : error  : Project "dragon-ball-online-tw-server-master\Tools\eUnzipper\eUnzipper.vcxproj" could not be found.

fatal error LNK1181: cannot open input file dragon-ball-online-tw-server-master\Build\Shared.lib

**Comment by ThatOneDBOGuy** [comment]
That project file is missing. You can always remove the project from the solution, so that there won't be any errors.

**Comment by Kadaz** [comment]
I tried that in vb 2015,2017,2019. I also remove the eunzipper from the project. Same error:  fatal error LNK1181: cannot open input file dragon-ball-online-tw-server-master\Build\Shared.lib. I'll wait for a better project files. Sorry for sorry for bothering you.

**Comment by Kadaz** [comment]
![image](https://user-images.githubusercontent.com/8410276/65266216-48978400-db1b-11e9-844c-52cf8856eac3.png)

**Comment by ThatOneDBOGuy** [comment]
It's no bother, at all. I'm willing to help. Did you make sure to build in Release x64?

**Comment by Kadaz** [comment]
I forgot to chance from debug x64 to release x64. it build succesfull. 
![image](https://user-images.githubusercontent.com/8410276/65268366-aaf28380-db1f-11e9-8f34-35a0820624c0.png)

Tnx a lot for your help!!!

**Comment by ThatOneDBOGuy** [comment]
You're welcome! :D
