### ISSUE TITLE
CommunityServer

### ISSUE THREAD

**Issue by Kadaz** [ivanlamega/dragon-ball-online-tw-server#4]
CommnityServer cant open. It shows Interapt signal (11) messege. Also chat not working in the game. 
config i use: xml version="1.0" encoding="utf-8"?>
<CommunityServer>
  
  
  <LogLevel Value="3"/>
  
  <ServerWorker Value="1"/>
  <Server IP="127.0.0.1" Port="50200" />
  <MySQL Host="127.0.0.1" Database="dragonball" User="root" Password="" />
  
  
  <CharServerList Count="1">
    <CharServer1 IP="127.0.0.1" Port="50300" />
  </CharServerList>
</CommunityServer>

I tried to change the ip in this line in the gamesocket.cpp tp localhost(127.0.0.1):
strcpy_s(res.achCommunityServerIP, sizeof(res.achCommunityServerIP), "127.0.0.1");
	res.wCommunityServerPort = 50500;
	res.timeDBOEnter = time(NULL);
Same problem. The rest of the files are working pretty good for me.

**Comment by Kadaz** [comment]
![image](https://user-images.githubusercontent.com/8410276/65288810-ce81f200-db50-11e9-9cf4-4ef9f8092e64.png)

Interapted signal and then closed

**Comment by ThatOneDBOGuy** [comment]
That's a segment violation code. Did you correctly configure the server?

**Comment by ThatOneDBOGuy** [comment]
Also, I think you should try debugging the Community Server to find the issue

**Comment by Kadaz** [comment]
I went in the community server xml and change this lines: 
  <CharServerList Count="1">
    <CharServer1 IP="127.0.0.1" Port="50300" />
  </CharServerList>
</CommunityServer>
to this: 
  <GameData Path="../Data/" />
</CommunityServer>. Now it opens like this: 
![image](https://user-images.githubusercontent.com/8410276/65336843-c026eb00-dbcf-11e9-8c3e-dd165378ea44.png) 
is it correct?

**Comment by Kadaz** [comment]
![image](https://user-images.githubusercontent.com/8410276/65336945-eea4c600-dbcf-11e9-9c80-0419f3262d84.png)

**Comment by ThatOneDBOGuy** [comment]
Replace line 8 with this:
<Server ID="1" ChannelID="1" IP="127.0.0.1" Port="50350" />

**Comment by Kadaz** [comment]
![image](https://user-images.githubusercontent.com/8410276/65337876-af777480-dbd1-11e9-83ae-dc80802e9bc6.png)

It show me nothing. can you send again?

**Comment by Kadaz** [comment]
Server ID="1" ChannelID="1" IP="127.0.0.1" Port="50500" i think you meen something like this

**Comment by ThatOneDBOGuy** [comment]
Yes, like that. You can change the port to 50350, as well.

**Comment by Kadaz** [comment]
alright

**Comment by Kadaz** [comment]
Its geting intresting. now community server crush whenether i try to chat in the game. Also it pops a mesage that the chat is disconnected. If i dont chat it doesnt crush.  I test it with both 50500 and 50350. Anyway, at least it opens.

**Comment by ThatOneDBOGuy** [comment]
In the source, where you change the IP for the community server, you can also change the port. By default the IP in the source is 50500. You can change it to 50350 to make it work.

**Comment by Kadaz** [comment]
I did that. I also rebuild thd project just for sure. Same resolts. It crush when i try to chat.

**Comment by ThatOneDBOGuy** [comment]
Hm.. that's a weird error. When I chat it seems to work. No problem! I'll see what the problem is.

**Comment by Kadaz** [comment]
I test a simular project that i found in the forum few months ago. It has the sane problem in the community. I beleive its a clieb bug. I` ll use this one from the dscription to check it.

**Comment by Kadaz** [comment]
Nope. Same crush.

**Comment by ThatOneDBOGuy** [comment]
Did you try debugging the community server in visual studio?

**Comment by Kadaz** [comment]
It works. Finaly. I reinstall the database with the updates you did a few hours ago.

**Comment by ThatOneDBOGuy** [comment]
That's good, haha. It was a weird problem. Glad everything worked out!
