### ISSUE TITLE
Questlist database

### ISSUE THREAD

**Issue by Zindel-Pam** [ivanlamega/dragon-ball-online-tw-server#7]
This lines: [Quest Lines](http://prntscr.com/p8vl7z) as a reference to a database that not exist in the sql files.

If I try to create a database with that fields I will obtain a disconeted signal 22

**Comment by ThatOneDBOGuy** [comment]
Oh, right I forgot to upload the database for that, haha. I'll commit it as soon as I get on my computer!

**Comment by ThatOneDBOGuy** [comment]
I uploaded a new database, so you can try it on there. It's part of the quest system I was working on but I didn't finish it since I was planning on working on quests last.

**Comment by Zindel-Pam** [comment]
I check the new dboupdate.sql but it don't has the structure for database "questlist"

**Comment by ThatOneDBOGuy** [comment]
I will add it in right now! Sorry for the inconvenience.

**Comment by ThatOneDBOGuy** [comment]
I updated the database! When you get the time, check to see if the new database works now.

**Comment by Zindel-Pam** [comment]
Hi, now works not crash and the quest are saving in the database. Good work 

PD: I added this code and database at source that I send to Ivan and works fine, nice to see more advances in quest developement
